# general settings
# name: debug_SRIQA_CSIQ
name: 001_SRIQA_CSIQ
model_type: SRIQAModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123
split_num: 10
save_final_results_path: './experiments/SRIQA_CSIQ_results.txt'

# dataset and data loader settings
datasets:
  val:
    name: CSIQ
    type: GeneralFR2NRDataset
    dataroot_target: ./datasets/CSIQ/dst_imgs
    dataroot_ref: ./datasets/CSIQ/src_imgs
    meta_info_file: ./datasets/meta_info/meta_info_CSIQDataset.csv
    mos_range: [0, 1]
    lower_better: true
    mos_normalize: true
    split_file: ./datasets/meta_info/csiq_seed123.pkl
    split_index: 2 # which split to use, start from 1


    augment:
      resize: [256, 256]
      center_crop: 224

# network structures
network:
  type: SRIQA
  #pretrained_model_path: ./experiments/BSRGAN/BSRGAN.pth
  #load_feature_weight_only: True
  pretrained_model_path: /root/autodl-fs/videomamba_pretrain_models/SRIQA_BACK/models/net_best_CSIQ_1conv_mlp.pth
  load_feature_weight_only: False

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: Adam
    lr: !!float 1e-3
    weight_decay: !!float 5e-4

  optim_finetune:
    type: Adam
    lr: !!float 1e-5
    weight_decay: !!float 5e-4

  scheduler:
    type: MultiStepLR
    milestones: [1000]
    gamma: 1

  scheduler_finetune:
    type: MultiStepLR
    milestones: [1000]
    gamma: 1

  total_iter: 12000
  finetune_start_iter: 60000
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
    type: MSELoss
    loss_weight: !!float 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 100
  save_img: false
  pbar: true
  save_score: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately
  metrics:
    srcc:
      type: calculate_srcc

    plcc:
      type: calculate_plcc

    krcc:
      type: calculate_krcc

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 2e3  # renyu: still need to save states for resume
  save_latest_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
