# renyu: ResNetIQA在LIVE数据集上训练的配置，跑train.py
# general settings
name: 001_ResNetIQA_LIVE
model_type: GeneralIQAModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

# dataset and data loader settings
datasets:
  train:
    name: LIVE
    type: GeneralFR2NRDataset
    dataroot_target: './datasets/LIVEIQA_release2'
    meta_info_file: './datasets/meta_info/meta_info_LIVEIQADataset.csv'
    mos_range: [1, 100]
    lower_better: true
    mos_normalize: true
    split_file: ./datasets/meta_info/live_seed123.pkl
    split_index: 2 # which split to use, start from 1

    # renyu: 控制下图像大小，缩放到320x320然后随机crop 224x224
    augment:
      hflip: true
      resize: [512, 512]
      #random_crop: 224
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: LIVE
    type: GeneralFR2NRDataset
    dataroot_target: './datasets/LIVEIQA_release2'
    meta_info_file: './datasets/meta_info/meta_info_LIVEIQADataset.csv'
    mos_range: [1, 100]
    lower_better: true
    mos_normalize: true
    split_file: ./datasets/meta_info/live_seed123.pkl
    split_index: 2 # which split to use, start from 1

    augment:
      resize: [512, 512]
      #center_crop: 224

    num_worker_per_gpu: 4
    batch_size_per_gpu: 8

# network structures
network:
  type: ResNetIQA
  freeze_resnet: false

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: AdamW
    lr: !!float 1e-3

  scheduler:
    type: MultiStepLR
    milestones: [10, 20, 30, 40]
    gamma: 0.5

  total_epoch: 50 
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
    type: MSELoss 
    loss_weight: !!float 1.0

# validation settings
val:
  val_freq: !!float 100
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately
  metrics:
    srcc:
      type: calculate_srcc

    plcc:
      type: calculate_plcc

    krcc:
      type: calculate_krcc

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2e3
  save_latest_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
